export const departments = [
  { nombre: "Abastecimiento" },
  { nombre: "Anatomía Patológica" },
  { nombre: "Anestesiología" },
  { nombre: "Banco Sangre" },
  { nombre: "Biomarcadores Onco" },
  { nombre: "Compras" },
  { nombre: "DESAM" },
  { nombre: "Diálisis" },
  { nombre: "Endocrinologia/Diabetes" },
  { nombre: "Equipos Médicos" },
  { nombre: "Farmacia" },
  { nombre: "Gastro" },
  { nombre: "Ginecologia" },
  { nombre: "Hemodinamia y Farmacia" },
  { nombre: "Histocompatibilidad" },
  { nombre: "Hospitalización Domiciliaria" },
  { nombre: "Hospitalizados" },
  { nombre: "Infertilidad" },
  { nombre: "Investigación" },
  { nombre: "Laboratorio Clínico" },
  { nombre: "Laboratorio DxM" },
  { nombre: "Microbiologia" },
  { nombre: "Neonatología" },
  { nombre: "Oncología" },
  { nombre: "Pabellón" },
  { nombre: "Pediatría" },
  { nombre: "Rayos" },
  { nombre: "Sala cuna" },
  { nombre: "Servicio de Salud" },
  { nombre: "Transplante" },
  { nombre: "UCI" },
  { nombre: "Urgencia Adultos" },
  { nombre: "Urgencia Pediatrica" },
  { nombre: "Virologia" },
  { nombre: "Distribuidores" },
  { nombre: "Industria" },
  { nombre: "SAR" },
  { nombre: "CESFAM" },
  { nombre: "Municipalidad" },
  { nombre: "Corporacion" },
  { nombre: "UCI Pediátrica" },
  { nombre: "UCI Pediatrica" },
  { nombre: "APS" },
  { nombre: "Posta Rural" },
];
